% Description: TIM Matlab interface debug build script
% Documentation: building_matlab.txt

mex tim_matlab.cpp ...
	-D_HAS_ITERATOR_DEBUGGING=0 ...
	-DPASTEL_ENABLE_PENSURES ...
	-DPASTEL_DEBUG_MODE ...
	-I'../../../pastel' ...
	-I'../../../tim' ...
	-I'../../../../external/boost_1_45_0' ...
	-L'../../../pastel/build/vs2008/lib' ...
	-L'../../../tim/build/vs2008/lib' ...
	-lTimMatlab_d ...
	-lTimCore_d ...
	-lPastelGeometry_d ...
	-lPastelMath_d ...
	-lPastelMatlab_d ...
	-lPastelSys_d ...
	-g
