% Description: TIM Matlab interface develop build script
% Documentation: building_matlab.txt

mex tim_matlab.cpp ...
	-D_HAS_ITERATOR_DEBUGGING=0 ...
	-DPASTEL_ENABLE_PENSURES ...
	-I'../../../pastel' ...
	-I'../../../tim' ...
	-I'../../../../external/boost_1_45_0' ...
	-L'../../../pastel/build/vs2008/lib' ...
	-L'../../../tim/build/vs2008/lib' ...
	-lPastelSys_v ...
	-lPastelMatlab_v ...
	-lPastelMath_v ...
	-lPastelGeometry_v ...
	-lTimCore_v ...
	-lTimMatlab_v

