mex timDifferentialEntropy.cpp ...
    -I'e:\ohjelmointi\hgproject\pastel_main\' ...
    -I'e:\ohjelmointi\hgproject\' ...
    -I'e:\ohjelmointi\external\boost_1_38' ...
    -L'e:\ohjelmointi\hgproject\pastel_main\pastel\lib' ...
    -L'e:\ohjelmointi\hgproject\tim\lib' ...
    -lpastelsys ...
    -lpastelmath ...
    -lpastelgeometry ...
    -lpasteldevice ...
    -lpasteldsp ...
    -lpastelgfx ...
    -ltimcore

mex timMutualInformation.cpp ...
    -I'e:\ohjelmointi\hgproject\pastel_main\' ...
    -I'e:\ohjelmointi\hgproject\' ...
    -I'e:\ohjelmointi\external\boost_1_38' ...
    -L'e:\ohjelmointi\hgproject\pastel_main\pastel\lib' ...
    -L'e:\ohjelmointi\hgproject\tim\lib' ...
    -lpastelsys ...
    -lpastelmath ...
    -lpastelgeometry ...
    -lpasteldevice ...
    -lpasteldsp ...
    -lpastelgfx ...
    -ltimcore

mex timMutualInformationNaive.cpp ...
    -I'e:\ohjelmointi\hgproject\pastel_main\' ...
    -I'e:\ohjelmointi\hgproject\' ...
    -I'e:\ohjelmointi\external\boost_1_38' ...
    -L'e:\ohjelmointi\hgproject\pastel_main\pastel\lib' ...
    -L'e:\ohjelmointi\hgproject\tim\lib' ...
    -lpastelsys ...
    -lpastelmath ...
    -lpastelgeometry ...
    -lpasteldevice ...
    -lpasteldsp ...
    -lpastelgfx ...
    -ltimcore
